---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fdk-rss-atom-feed
  labels:
    app: fdk-rss-atom-feed
spec:
  template:
    spec:
      containers:
        - name: fdk-rss-atom-feed
          env:
            - name: FDK_BASE_URI
              valueFrom:
                secretKeyRef:
                  name: commonurl-staging
                  key: FDK_BASE_URI
            - name: SEARCH_API
              valueFrom:
                secretKeyRef:
                  name: commonurl-staging
                  key: FDK_SEARCH_SERVICE_BASE_URI
