name: Deploy to staging
permissions:
  contents: read
  packages: write
on:
  pull_request:
    types: [ready_for_review, opened, reopened, synchronize]
    branches:
      - main

jobs:
  dependabot-build:
    name: Build image on PR from dependabot
    if: ${{ github.actor == 'dependabot[bot]' }}
    uses: Informasjonsforvaltning/workflows/.github/workflows/build.yaml@main

  build-fdk-rss-atom-feed:
    name: Build when pull request is created
    if: ${{ github.actor != 'dependabot[bot]' && github.event.pull_request.draft == false }}
    uses: Informasjonsforvaltning/workflows/.github/workflows/build-push-nox.yaml@main
    with:
      app_name: fdk-rss-atom-feed
      python_version: "3.12"
      python_architecture: x64
      environment: staging
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy to staging environment
    if: github.event.pull_request.draft == false
    needs: [build-fdk-rss-atom-feed]
    uses: Informasjonsforvaltning/workflows/.github/workflows/kustomize-deploy.yaml@main
    with:
      app_name: fdk-rss-atom-feed
      environment: staging
      cluster: digdir-fdk-dev
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DIGDIR_FDK_AUTODEPLOY: ${{ secrets.DIGDIR_FDK_DEV_AUTODEPLOY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
